version: "3.9"
services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - backend

  communication-control:
    image: ghcr.io/levastian/hiveemulator/communication-control:latest
    container_name: com-control
    restart: always
    environment:
      Redis__ConnectionString: "redis:6379"
      ASPNETCORE_URLS: "http://+:8080,http://+:9090"
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - redis

  map-client:
    image: ghcr.io/levastian/hiveemulator/map-client:latest
    container_name: map-client
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config.json:/usr/share/nginx/html/config.json:ro
    networks:
      - backend
    depends_on:
      - communication-control

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    networks:
      - backend

networks:
  backend:
    driver: bridge
